// export const FETCH_TODOS = "FETCH_TODOS"
export const TODOS_START = "TODOS_START"
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS"
export const TODOS_FAIL = "TODOS_FAIL"
export const ADD_TODOS_SUCCESS = "ADD_TODOS_SUCCESS"
export const COMPLETE_TODOS_SUCCESS = "COMPLETE_TODOS_SUCCESS"
export const DELETE_TODOS_SUCCESS = "DELETE_TODOS_SUCCESS"
export const UPDATE_TODOS_SUCCESS = "UPDATE_TODOS_SUCCESS"

export const AUTH_AUTO_LOGIN_CHECK = "AUTH_AUTO_LOGIN_CHECK"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const DO_NOTHING = "DO_NOTHING"





